let imagenes = [];
imagenes.push("Afghanistan-01.png");
imagenes.push("Albania-01.png");
imagenes.push("Algeria-01.png");
imagenes.push("Andorra-01.png");
imagenes.push("Angola-01.png");
imagenes.push("Antigua and Barbuda-01.png");
imagenes.push("Argentina-01.png");
imagenes.push("Armenia-01.png");
imagenes.push("Australia-01.png");
imagenes.push("Austria-01.png");
imagenes.push("Azerbaijan-01.png");
imagenes.push("Bahamas-01.png");
imagenes.push("Bahrain-01.png");
imagenes.push("Bangladesh-01.png");
imagenes.push("Barbados-01.png");
imagenes.push("Belarus-01.png");
imagenes.push("Belgium-01.png");
imagenes.push("Benin-01.png");
imagenes.push("Bhutan-01.png");
imagenes.push("Bolivia-01.png");
imagenes.push("Bosnia and Herzegovina-01.png");
imagenes.push("Botswana-01.png");
imagenes.push("Brazil-01.png");
imagenes.push("Brunei-01.png");
imagenes.push("Bulgaria-01.png");
imagenes.push("Burkina Faso-01.png");
imagenes.push("Burundi-01.png");
imagenes.push("Cambodia-01.png");
imagenes.push("Cameroon-01.png");
imagenes.push("Canada-01.png");
imagenes.push("Cape Verde-01.png");
imagenes.push("Central African Republic-01.png");
imagenes.push("Chad-01.png");
imagenes.push("Chile-01.png");
imagenes.push("China-01.png");
imagenes.push("Colombia-01.png");
imagenes.push("Comoros-01.png");
imagenes.push("Congo Democratic Republic.png");
imagenes.push("Congo-01.png");
imagenes.push("Costa Rica-01.png");
imagenes.push("Croatia-01.png");
imagenes.push("Cuba-01.png");
imagenes.push("Cyprus-01.png");
imagenes.push("Czech Republic-01.png");
imagenes.push("Denmark-01.png");
imagenes.push("Djbouti-01.png");
imagenes.push("Dominica-01.png");
imagenes.push("Dominican Republic-01.png");
imagenes.push("East Timor-01.png");
imagenes.push("Ecuador-01.png");
imagenes.push("Egypt-01.png");
imagenes.push("El Salvador-01.png");
imagenes.push("England-01.png");
imagenes.push("Eritrea-01.png");
imagenes.push("Estonia-01.png");
imagenes.push("Ethiopia-01.png");
imagenes.push("Europe-01.png");
imagenes.push("Finland-01.png");
imagenes.push("France-01.png");
imagenes.push("Gabon-01.png");
imagenes.push("Gambia-01.png");
imagenes.push("Georgia-01.png");
imagenes.push("Germany-01.png");
imagenes.push("Ghana-01.png");
imagenes.push("Greece-01.png");
imagenes.push("Greenland-01.png");
imagenes.push("Grenada-01.png");
imagenes.push("Guinea Bissau-01.png");
imagenes.push("Guinea-01.png");
imagenes.push("Guyane-01.png");
imagenes.push("Haiti-01.png");
imagenes.push("Honduras-01.png");
imagenes.push("Hong Kong-01.png");
imagenes.push("Hungary-01.png");
imagenes.push("Iceland-01.png");
imagenes.push("India-01.png");
imagenes.push("Indonesia-01.png");
imagenes.push("Iran-01.png");
imagenes.push("Iraq-01.png");
imagenes.push("Ireland-01.png");
imagenes.push("Israel-01.png");
imagenes.push("Italy-01.png");
imagenes.push("Ivory Coast-01.png");
imagenes.push("Jamaica-01.png");
imagenes.push("Japan Ensign-01.png");
imagenes.push("Japan-01.png");
imagenes.push("Jordan-01.png");
imagenes.push("Kazakhstan-01.png");
imagenes.push("Kuwait-01.png");
imagenes.push("Kyrgyzstan-01.png");
imagenes.push("Laos-01.png");
imagenes.push("Latvia-01.png");
imagenes.push("Lebanon-01.png");
imagenes.push("Liberia-01.png");
imagenes.push("Libya-01.png");
imagenes.push("Liechtenstein-01.png");
imagenes.push("Lithuania-01.png");
imagenes.push("Luxembourg-01.png");
imagenes.push("Macedonia-01.png");
imagenes.push("Madagascar-01.png");
imagenes.push("Malaysia-01.png");
imagenes.push("Mali-01.png");
imagenes.push("Mauritius-01.png");
imagenes.push("Mexico-01.png");
imagenes.push("Monaco-01.png");
imagenes.push("Mongolia-01.png");
imagenes.push("Morocco-01.png");
imagenes.push("Myanmar-01.png");
imagenes.push("Namibia-01.png");
imagenes.push("Netherlands-01.png");
imagenes.push("New Zealand-01.png");
imagenes.push("Niger-01.png");
imagenes.push("Nigeria-01.png");
imagenes.push("nombres.txt");
imagenes.push("North Holland-01.png");
imagenes.push("North Korea-01.png");
imagenes.push("Norway-01.png");
imagenes.push("Pakistan-01.png");
imagenes.push("Palau-01.png");
imagenes.push("Palestine-01.png");
imagenes.push("Panama-01.png");
imagenes.push("Peru-01.png");
imagenes.push("Philippines-01.png");
imagenes.push("Poland-01.png");
imagenes.push("Portugal-01.png");
imagenes.push("Puerto Rico-01.png");
imagenes.push("Qatar-01.png");
imagenes.push("Romania-01.png");
imagenes.push("Russia-01.png");
imagenes.push("Rwanda-01.png");
imagenes.push("Saba-01.png");
imagenes.push("Saudi Arabia-01.png");
imagenes.push("Scandinavian Union-01.png");
imagenes.push("Senegal-01.png");
imagenes.push("Sierra Leone-01.png");
imagenes.push("Singapore-01.png");
imagenes.push("Slovakia-01.png");
imagenes.push("Somalia-01.png");
imagenes.push("South Korea-01.png");
imagenes.push("South Ossetia-01.png");
imagenes.push("Spain-01.png");
imagenes.push("Sudan-01.png");
imagenes.push("Sweden-01.png");
imagenes.push("Switzerland-01.png");
imagenes.push("Syria-01.png");
imagenes.push("Taiwan-01.png");
imagenes.push("Tajikistan-01.png");
imagenes.push("Tanzania-01.png");
imagenes.push("Thailand-01.png");
imagenes.push("Togo-01.png");
imagenes.push("Tonga-01.png");
imagenes.push("Trinidad and Tobago-01.png");
imagenes.push("Tunisia-01.png");
imagenes.push("Turkey-01.png");
imagenes.push("Ukraine-01.png");
imagenes.push("United Arab Emirates-01.png");
imagenes.push("United Kingdom-01.png");
imagenes.push("United States of America-01.png");
imagenes.push("Uruguay-01.png");
imagenes.push("Venezuela-01.png");
imagenes.push("Vietnam-01.png");
imagenes.push("Yemen-01.png");

function aleatorio(mayor) {
  return Number.parseInt(Math.random() * mayor);
}

function shuffle(a) {
  var j, x, i;
  for (i = a.length - 1; i > 0; i--) {
    j = Math.floor(Math.random() * (i + 1));
    x = a[i];
    a[i] = a[j];
    a[j] = x;
  }
  return a;
}

window.onload = () => {
  var html = "<img src='img/";
  html += imagenes[aleatorio(imagenes.length)];
  html += "' />";
  bandera.innerHTML = html;
  //alert(html);
};
